config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord

 has_many :posts
 has_many :cars
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def index
  end
  def show
  end
end

app/controllers/posts_controller.rb
class PostsController < ActionController::Base
  protect_from_forgery with: :exception
  def index
    @posts = Post.all
    @post = Post.new
  end
  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def update
    @post = Post.find(params[:id])
    @post.update(
      name: params[:post][:name],
      title: params[:post][:title],
      year: params[:post][:year])
    redirect_to action: :show
  end

  def edit
    @post = Post.find(params[:id])

  end

  def create
    @post = Post.create(
      name: params[:post][:name],
      title: params[:post][:title],
      user_id: User.last.id,
    year: params[:post][:year])
    redirect_to @post
  end

  def destroy
    Post.find(params[:id]).delete
    redirect_to action: :index
  #   redirect_to :action => :index
  #
  #   array:
  #   a =[1, 2, 3]
  #   a.first: a[0]
  #   a[1]
  #   a[2]
  #
  #   hash = {a: :b, c: :d}
  #   hash[:a] = :b
  #   hash[:c]= :d
  #
  #   active record: rails model
  #   user = User.create(name: 'judy', email: 'judy@fresho.com')
  #   user.name
  #   user.email
  end
end

app/controllers/users_controller.rb
class UsersController < ActionController::Base
  protect_from_forgery with: :exception
  def index
    @users = User.all
    @user = User.new
  end
  def show
    @user = User.find(params[:id])
    @posts = @user.posts
    @cars = @user.cars
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(
      name: params[:user][:name],
      email: params[:user][:email],
      age: params[:user][:age])
    redirect_to @user
  end

  def destroy
    User.find(params[:id]).delete
    redirect_to :action => :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TamerFirstApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>Create your post</h1>

<div class="row">
  <%= form_for(@post) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, placeholder: 'your name', class: 'form-control' %>
    <%= f.label :title %>
    <%= f.text_field :title, placeholder: 'your title', class: 'form-control' %>
    <%= f.label :year %>
    <%= f.range_field :year, in: 2000..2019, placeholder: '2000-2019', class: 'form-control' %>
    <%= f.submit "Update", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
 <p><%= post.name %></p>
 <p><%= post.title %></p>
 <p><%= post.year %></p>

 <%= button_to 'Delete', post, method: :delete, data: {confirm: 'Are you sure?'} %>

 <% end %>

<%= link_to 'Add', new_post_url(@post) %>

app/views/posts/new.html.erb
<h1>Create your post</h1>

<div class="row">
  <%= form_for(@post) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>

    <%= f.submit "Create", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/posts/show.html.erb
<p><%= @post.name %></p>
<p><%= @post.title %></p>
<p><%= @post.year %></p>
<%= button_to 'Delete', @post, method: :delete, data: {confirm: 'Are you sure?'} %>
<%= link_to 'Edit', edit_post_url(@post) %>

app/views/users/index.html.erb
<% @users.each do |user| %>
 <p><%= user.name %></p>
 <p><%= user.email %></p>
 <p><%= user.age %></p>
 <%= button_to 'Delete', user, method: :delete, data: {confirm: 'Are you sure?'} %>
<% end %>

<%= link_to "Add", new_user_url(@user) %>

app/views/users/new.html.erb
<h1>Create your user</h1>

<div class="row">
  <%= form_for(@user) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, placeholder: 'name', class: 'form-control' %>
    <%= f.label :email %>
    <%= f.email_field :email,placeholder: 'email', class: 'form-control' %>
    <%= f.label :age %>
    <%= f.range_field :age, in: 1..120, placeholder: '0-100', class: 'form-control' %>
    <%= f.submit "Create", class: "btn btn-primary" %>
<% end %>
</div>

app/views/users/show.html.erb
<p><%= @user.name %></p>
<p><%= @user.email %></p>
<p><%= @user.age %></p>
<%= button_to 'Delete', @user, method: :delete, data: {confirm: 'Are you sure?'} %>

<h3>All Posts</h3>
<% @posts.each do |post| %>
  <p><%= post.name %>
  <p><%= post.title %>
<% end %>

<h3>All Cars</h3>
<% @cars.each do |car| %>
  <p><%= car.model %>
  <p><%= car.colour %>
<% end %>